[workspace]
members  = [ "contracts/fund", "contracts/mocks/*", "contracts/redemption", "contracts/strategy", "packages/*" ]
resolver = "2"

[workspace.package]
edition      = "2021"
rust-version = "1.78.0"
version      = "0.1.1"

[workspace.dependencies]
cosmrs            = { version = "0.20.0" }
cosmwasm-schema   = { version = "2.1.4" }
cosmwasm-std      = { version = "2.1.4", features = [ "abort", "cosmwasm_1_2", "cosmwasm_1_3", "cosmwasm_1_4", "cosmwasm_2_0", "iterator", "stargate" ] }
cw-controllers    = { version = "2.0.0" }
cw-storage-plus   = { version = "2.0.0" }
cw-utils          = { version = "2.0.0" }
cw-vault-standard = { package = "cw-vault-standard-margined", version = "2.0.0" }
cw2               = { version = "2.0.0" }
cw_margined       = { version = "2.0.0" }
neutron-std       = { package = "margined-neutron-std", version = "5.1.3" }
neutron-test-tube = { version = "5.1.3" }
num_enum          = { version = "0.7.2" }
osmosis-std       = { version = "0.26.0" }
prost             = { version = "0.13.3" }
prost-types       = { version = "0.13.3" }
regex             = { version = "1.10.5" }
serde             = { version = "1.0.201" }
serde-json-wasm   = { version = "1.0.1" }
serde_json        = { version = "1.0.117" }
strum             = { version = "0.26.2", features = [ "derive" ] }
test-tube         = { package = "test-tube-ntrn", version = "0.1.7" }
thiserror         = { version = "1.0.44" }
vaultenator       = { version = "2.0.1" }

# packages
interface = { version = "0.1.0", path = "packages/interface" }
testing   = { version = "0.1.0", path = "packages/testing" }

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true
panic            = 'abort'
rpath            = false
