[package]
authors = [ "Margined Protocol" ]
edition = "2021"
name    = "strategy"
version = "0.0.1"

exclude = [
 # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
 "contract.wasm",
 "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
backtraces = [ "cosmwasm-std/backtraces" ]
default    = [ "astroport" ]
# default    = [ "osmosis" ]
library = [  ]

astroport = [  ]
osmosis   = [  ]

[package.metadata.optimizer]
builds        = [ { name = "astroport", default-features = false }, { name = "osmosis", default-features = false } ]
default-build = true

[dependencies]
cosmwasm-schema   = { workspace = true }
cosmwasm-std      = { workspace = true }
cw-storage-plus   = { workspace = true }
cw-utils          = { workspace = true }
cw-vault-standard = { workspace = true }
cw2               = { workspace = true }
interface         = { workspace = true }
osmosis-std       = { workspace = true }
prost             = { workspace = true }
serde             = { workspace = true }
thiserror         = { workspace = true }

[dev-dependencies]
osmosis-test-tube = { workspace = true }
test-tube         = { workspace = true }
testing           = { workspace = true }
